fixed extension typo

diff --git a/.github/workflows/buildAndTest.yml b/.github/workflows/buildAndTest.yml
--- a/.github/workflows/buildAndTest.yml
+++ b/.github/workflows/buildAndTest.yml
@@ -198,7 +198,7 @@ jobs:
           export PYTHONPATH=$PYTHONPATH:$PWD/src
           make test-sw
           if [ ! -f software_report.html ]; then
-            echo "software_report.html not found!"
+            echo "software_report.xml not found!"
             ls
             exit 1
           fi
@@ -210,7 +210,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: software_report 
-          path: software_report.html
+          path: software_report.xml
           if-no-files-found: error 
           overwrite: true 
 
@@ -301,6 +301,11 @@ jobs:
             echo "PYTHONPATH is ${PYTHONPATH}"
             export PYTHONPATH=$PYTHONPATH:$PWD/src
             just test-hw
+            # if [ ! -f hardware_report.html ]; then
+            #   echo "hardware_report.xml not found!"
+            #   ls
+            #   exit 1
+            # fi
 
       # -----------
       # TODO: Upload hardware regression test artifacts 
@@ -309,7 +314,7 @@ jobs:
       #   uses: actions/upload-artifact@v4
       #   with:
       #     name: hardware_report 
-      #     path: hardware_report.html
+      #     path: hardware_report.xml
       #     if-no-files-found: error 
       #     overwrite: true 
 
