Refactor and rebuild pruning (#519)
* further docs and integration with myst

* docs

* conflict resolve

* add metadata tests

* doc

* add missing passes

* finished analysis pass tests, found a few corner cases

* doc update

* renaming

* wip add meta

* big refactor on common meta data; size is renamed to shape, this might break stuff, tested against the test/passes script

* variable name bug fix

* fix total-bits

* make add_value optional and various fixes on pass_args

* minors

* rename pass, the previous name is confusing...it is not calculating total bits...

* format

* missing files

* quantize tests

* checked all analysis passs now passing using pytest command: python3 -m pytest --log-level=DEBUG --verbose -n 0 --cov=machop/chop/ --cov-report=html --html=report.html --self-contained-html --profile --profile-svg test/passes/graph/analysis

* rename total-bits

* test for each pass for better printouts on pytest

* minors

* formatting..

* format

* fix broken vgg7, added support force_deivce_meta in add_common_metadata

* pruning done

* minor

* formatting

* forgot to format test files...

* format

* Added error detection in building docs (#514)

* Added error detection in building docs

* Fixed missed ci tests

* added exit

* Removed breakpoint for testing

* test if doc errors are captured

* Fixed python format error

* Added build doc with errors

* add missing test cases

* updated doc for getting started

* reformat..

* fixed path error

* clean up all sphinx warnings and bugs

* screw this formatter thingy... why the hack it misses..

---------

Co-authored-by: Aaron-Zhao123 <aaronzhao@gmail.com>
Co-authored-by: Jianyi Cheng <jianyi.cheng@cl.cam.ac.uk>

diff --git a/.github/workflows/buildDoc.yml b/.github/workflows/buildDoc.yml
--- a/.github/workflows/buildDoc.yml
+++ b/.github/workflows/buildDoc.yml
@@ -41,9 +41,12 @@ jobs:
       - name: Build sphinx html
         run: |
           cd machop/sphinx_docs
-          make html
+          make html 2>&1 | tee html.log
+          # temporarily - still launch doc with errors
+          ghp-import -n -p -f build/html
+          ! grep -rn html.log -e "Error" || exit 1
 
-      - name: Run ghp-import
-        run: |
-          ghp-import -n -p -f machop/sphinx_docs/build/html
+      # - name: Run ghp-import
+      #   run: |
+      #     ghp-import -n -p -f machop/sphinx_docs/build/html
 
